spring:
  application:
    name: IRMS
  server:
    port: ${SERVER_PORT:8080}
  cors:
    allowed-origins:
      - ${FRONTEND_URL}
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers:
      - "*"
    exposed-headers:
      - Authorization
      - Content-Type
    allow-credentials: true
    max-age: 3600
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    defer-datasource-initialization: true #Ensures DB is ready before JPA runs
    hibernate:
      ddl-auto: update #auto create and update table
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true #Logs SQL queries to console
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_size: 20
      hibernate.order_inserts: true
      hibernate.order_updates: true
jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: 604800000 # 7 days
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
